version: '3.8'

services:
  auth-postgres-test:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test_auth
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U test']
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - auth-postgres-test-data:/var/lib/postgresql/data
    networks:
      - auth-test-network

  auth-neo4j-test:
    image: neo4j:4.4
    environment:
      NEO4J_AUTH: neo4j/test
      NEO4J_ACCEPT_LICENSE_AGREEMENT: 'yes'
    ports:
      - '7474:7474'
      - '7687:7687'
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:7474 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    volumes:
      - auth-neo4j-test-data:/data
    networks:
      - auth-test-network

  auth-service:
    build: .
    environment:
      DB_HOST: auth-postgres-test
      DB_PORT: 5432
      DB_USER: test
      DB_PASSWORD: test
      DB_NAME: test_auth
      NEO4J_URI: bolt://auth-neo4j-test:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: test
      NODE_ENV: test
    depends_on:
      auth-postgres-test:
        condition: service_healthy
      auth-neo4j-test:
        condition: service_healthy
    ports:
      - '3002:3001'
    networks:
      - auth-test-network

volumes:
  auth-postgres-test-data:
  auth-neo4j-test-data:

networks:
  auth-test-network:
    driver: bridge